INSERT INTO users VALUES
(9,'David','Australia','2025-04-01');

select * from users;

-- Business Problem 1
-- Show every customer's name along with the amount they spent on each order.
select u.name,o.amount from users u join orders o
on u.user_id = o.user_id;

-- Business Problem 2
-- Show every customer's name along with the date of each order.
select u.name,o.order_date from users u join orders o 
on u.user_id = o.user_id;

-- Business Problem 3
-- Show every customer's name, country, and order amount.
select u.name,u.country,o.amount from users u join orders o on 
u.user_id = o.user_id;

-- Business Problem 4 
-- Calculate the total revenue generated by each customer.
select u.name,u.user_id,sum(o.amount) as total_revenue
 from users u join 
orders o on 
u.user_id = o.user_id 
group by 1,2;

-- Business Problem 5 
-- Calculate the average order value for each customer.
select u.name,u.user_id,avg(o.amount) as avg_order from users u 
join orders o on 
u.user_id = o.user_id 
group by 1,2;

-- Business Problem 6 
-- Find the highest purchase amount made by each customer.
select u.name,u.user_id, max(o.amount) as highest_purchase from users u 
join orders o on 
u.user_id = o.user_id 
group by u.name,u.user_id
order by highest_purchase desc;

-- Business Problem 7
-- Find the lowest purchase amount made by each customer.
select u.name,u.user_id,min(o.amount) as lowest_purchase from users u 
join orders o on 
u.user_id = u.user_id
group by 1,2
order by lowest_purchase asc;

-- Business Problem 8
-- Count how many orders each customer has placed.
select u.user_id,u.name,count(o.order_id) as order_count from users u 
join orders o on 
u.user_id = o.user_id 
group by 1,2
order by order_count desc;

-- Business Problem 9
-- Rank customers from highest revenue to lowest revenue.
select u.user_id,u.name,sum(o.amount) as revenue 
from users u join orders o on
u.user_id = o.user_id
group by 1,2
order by revenue desc;

-- Business Problem 10
-- Rank customers from highest average order value to lowest average order value.
select u.user_id,u.name,avg(o.amount) as avg_revenue 
from users u join orders o on
u.user_id = o.user_id
group by 1,2
order by avg_revenue desc;

-- Business Problem 11
-- Identify customers who have generated more than ₹500 in total revenue.
select u.name,u.user_id,sum(o.amount) as revenue_above_500 
from users u join orders o 
on u.user_id = o.user_id 
group by 1,2
having revenue_above_500 > 500
order by revenue_above_500 desc;

-- Business Problem 12
-- Identify customers who have placed more than one order.
select u.user_id,u.name,count(o.order_id) as order_list
from users u join orders o 
on u.user_id = o.user_id 
group by 1,2
having order_list > 1
order by order_list desc;

-- Business Problem 13
-- Show all registered users, including those who have never placed an order.
select u.user_id,u.name,count(o.order_id) as order_list from users u left join orders o 
on u.user_id = o.user_id 
group by 1,2;

-- Business Problem 14
-- Identify users who have never placed an order.
select u.user_id,u.name,count(o.order_id) as order_list from users u left join orders o 
on u.user_id = o.user_id 
group by 1,2
having order_list = 0;

-- Business Problem 15
-- Count how many users have never placed an order.
select count(*) as cold_users 
from users u left join orders o on 
u.user_id = o.user_id 
where o.order_id is null;




